---
title: "UC-MAIT analysis"
output:
  pdf_document: default
  html_document: default
---

```{r fig.width=22, fig.height=25, warning=FALSE, error=FALSE, message=FALSE, echo=FALSE, comment=NA}
knitr::opts_knit$set(global.par = TRUE)
```

```{r fig.width=22, fig.height=25, warning=FALSE, error=FALSE, message=FALSE, echo=FALSE, comment=NA}
library(plyr)
library(ggplot2)
library(RColorBrewer)
library(reshape2)
library(gplots)
library(gtools)
library(stats)
library(lattice)
library(latticeExtra)
library(grid)
library(gridExtra)
library(Rtsne)
```


```{r fig.width=22, fig.height=25, warning=FALSE, error=FALSE, message=FALSE, echo=FALSE, comment=NA}

## set baseDir if Knitting with RStudio button
baseDir <- "~/Desktop/Su Lab/UC-MAIT/"

## sets path if run from runAnalysis.R
#currentFile <- rstudioapi::getActiveDocumentContext()$path
#baseDir <- gsub("single_cell_insulin/.*", "single_cell_insulin/", currentFile)

#### source function scripts ####
funcDir <- paste(baseDir, "src/functions/", sep="")
funcFiles <- c("formatRaw.R", 
               "dataLoadUCMAIT.R", 
               "cleanCt.R", 
               "geneSetEnrichment.R", 
               "violinPlot.R", 
               "heatmap2_custom.R",
               "heatmap.3.R",
               "clusterFilter.R",
               "tableBarPlots.R",
               "clusterReport.R",
               "reportViolins.R",
               "reportTSNE.R",
               "plotTSNE.R")
funcFiles <- paste(funcDir, funcFiles, sep="")
for(file in funcFiles){
  source(file)
}

```


```{r fig.width=22, fig.height=25, warning=FALSE, error=FALSE, message=FALSE, echo=FALSE, comment=NA}
## load data
ctTable <- dataLoadUCMAIT()

## remove blood samples for now
#ctTable <- subset(ctTable, cellSource != "PB")

## calculate log2Ex, reformat ctTable, and normalize values
ctNorm <- cleanCt(ctTable, summaryOutput=T, cumExpCutoff = F, normGene = "none")

```


```{r fig.width=22, fig.height=25, warning=FALSE, error=FALSE, message=FALSE, echo=FALSE, comment=NA}
## cluster and filter
# ctClust <- clusterFilter(ctNorm, testK = F, numCenters = 6, plotHeatmap=F, plotClustOnly=F,
#                           heatmapFactor = "kmeans.cluster", heatmapColorBy = "source",
#                           heatmapTissueLabel = "insulin samples", 
#                           fisherTests = c("probe", "tissue", "age", "mouse"),
#                           cumulativeExpHist = F, filterClusters = T, clustersToRemove = c(1, 2, 5))
# 
# 
# ## cluster again to check performance
# ctClust <- subset(ctClust, select = -kmeans.cluster)
# ctClust <- clusterFilter(ctClust, testK = F, numCenters = 6, plotHeatmap=T, plotClustOnly=F, 
#                           heatmapFactor = "kmeans.cluster", 
#                           heatmapColorBy = c("age", "source", "probe"),
#                           heatmapTissueLabel = "filtered insulin samples", 
#                           fisherTests = c("probe", "tissue", "age", "mouse", "probe.age", "probe.tissue", "age.tissue", "probe.tissue.age"),
#                           cumulativeExpHist = F, filterClusters = F, clustersToRemove = NULL)
ctClust <- clusterFilter(ctNorm, testK = T, numCenters = 9, plotHeatmap=T, plotClustOnly=F,
                          heatmapFactor = "kmeans.cluster", heatmapColorBy = c("age", "probe"),
                          heatmapTissueLabel = "UCMAIT samples",
                          fisherTests = c("probe", "tissue", "age"),
                         # fisherTests = NULL,
                          cumulativeExpHist = T, filterClusters = T, clustersToRemove = c(6))
```


```{r fig.width=22, fig.height=25, warning=FALSE, error=FALSE, message=FALSE, echo=FALSE, comment=NA}
ctClust <- subset(ctClust, select = -kmeans.cluster)
ctClust <- clusterFilter(ctClust, testK = T, numCenters = 8, plotHeatmap=T, plotClustOnly=F,
                          heatmapFactor = "kmeans.cluster",
                          heatmapColorBy = c("age", "probe"),
                          heatmapTissueLabel = "filtered UCMAIT samples",
                          fisherTests = c("probe", "tissue", "age"),
                         # fisherTests = NULL,
                          cumulativeExpHist = T, filterClusters = F, clustersToRemove = NULL)


## cluster again to check performance
# ctClust <- subset(ctClust, select = -kmeans.cluster)
# ctClust <- clusterFilter(ctClust, testK = T, numCenters = 5, plotHeatmap=T, plotClustOnly=F, 
#                           heatmapFactor = "kmeans.cluster", 
#                           heatmapColorBy = c("age", "source", "probe"),
#                           heatmapTissueLabel = "filtered insulin samples", 
#                           fisherTests = c("probe", "tissue", "age", "mouse", "probe.age", "probe.tissue", "age.tissue", "probe.tissue.age"),
#                          # fisherTests = NULL,
#                           cumulativeExpHist = T, filterClusters = T, clustersToRemove = c(4))

# ctClust <- subset(ctClust, select = -kmeans.cluster)
# ctClust <- clusterFilter(ctClust, testK = T, numCenters = 4, plotHeatmap=T, plotClustOnly=F,
#                           heatmapFactor = "kmeans.cluster",
#                           heatmapColorBy = c("age", "source", "probe"),
#                           heatmapTissueLabel = "filtered insulin samples",
#                           fisherTests = c("probe", "tissue", "age", "mouse", "probe.age", "probe.tissue", "age.tissue", "probe.tissue.age"),
#                           cumulativeExpHist = T, filterClusters = F, clustersToRemove = NULL)


```


```{r fig.width=22, fig.height=25, warning=FALSE, error=FALSE, message=FALSE, echo=FALSE, comment=NA}
#### t-sne reports ####
plotTSNE(ctClust, colorby = c("kmeans.cluster", "probe", "patient", "age"))
```



```{r fig.width=22, fig.height=25, warning=FALSE, error=FALSE, message=FALSE, echo=FALSE, comment=NA}
#### violins ####

## Differentially expressed genes between cluster
violinPlot(ctGenes=ctClust, 
           byFactor="kmeans.cluster", 
           factorOrder=c(1:8),
           groupLabel="clusters", 
           extraLabel="for human samples",
           dotSize = 1.5, 
           dotAlpha = 0.3)

##  Differentially expressed genes between patients
violinPlot(ctGenes=ctClust, 
           byFactor="probe", 
           factorOrder=c("UCM5", "UCM6", "UCM10", "UCM12", "UCM13", "UCM14", "UCM15", "UCM16", "UCM17", "NBD1", "NBD3", "NBD4"),
           groupLabel="patients", 
           extraLabel="for human samples",
           dotSize = 1.5, 
           dotAlpha = 0.3)

##  Differentially expressed genes between phenotypes
# violinPlot(ctGenes=ctClust, 
#            byFactor="patient", 
#            factorOrder=c("UCM", "NBD"),
#            groupLabel="phenotypes", 
#            extraLabel="for human samples",
#            dotSize = 1.5, 
#            dotAlpha = 0.3)

##  Differentially expressed genes between tissues
violinPlot(ctGenes=ctClust, 
           byFactor="cellSource", 
           factorOrder=c("blood", "tissue"),
           groupLabel="tissues", 
           extraLabel="for human samples",
           dotSize = 1.5, 
           dotAlpha = 0.3)

##  Differentially expressed genes between tissues
violinPlot(ctGenes=ctClust, 
           byFactor="age", 
           factorOrder=c("blood", "infl", "uninfl"),
           groupLabel="tissues", 
           extraLabel="for human samples",
           dotSize = 1.5, 
           dotAlpha = 0.3)


#### bottom ####
```




